package com.example.pinkmoney.ui.theme

import androidx.compose.ui.graphics.Color

val PinkPrimaryDark = Color(0xFFFFB1C2)
val PinkOnPrimaryDark = Color(0xFF601124)
val PinkPrimaryContainerDark = Color(0xFF84263A)
val PinkOnPrimaryContainerDark = Color(0xFFFFD9DF)
val PinkSecondaryDark = Color(0xFFAEDFD4)
val PinkOnSecondaryDark = Color(0xFF123B35)
val PinkSecondaryContainerDark = Color(0xFF24564E)
val PinkOnSecondaryContainerDark = Color(0xFFC9F6EC)
val PinkBackgroundDark = Color(0xFF101114)
val PinkSurfaceDark = Color(0xFF1A1C20)
val PinkSurfaceVariantDark = Color(0xFF24272E)
val PinkOnSurfaceDark = Color(0xFFF2F3F7)
val PinkOnSurfaceVariantDark = Color(0xFFC4C7D0)
val PinkOutlineDark = Color(0xFF3B3F48)

val PinkPrimaryLight = Color(0xFFB92F4D)
val PinkOnPrimaryLight = Color(0xFFFFFFFF)
val PinkPrimaryContainerLight = Color(0xFFFFD9DF)
val PinkOnPrimaryContainerLight = Color(0xFF400716)
val PinkSecondaryLight = Color(0xFF3F665E)
val PinkOnSecondaryLight = Color(0xFFFFFFFF)
val PinkSecondaryContainerLight = Color(0xFFC9F6EC)
val PinkOnSecondaryContainerLight = Color(0xFF00201B)
val PinkBackgroundLight = Color(0xFFFFFBFF)
val PinkSurfaceLight = Color(0xFFFFFFFF)
val PinkSurfaceVariantLight = Color(0xFFF1F3F6)
val PinkOnSurfaceLight = Color(0xFF1B1B1F)
val PinkOnSurfaceVariantLight = Color(0xFF5D6169)
val PinkOutlineLight = Color(0xFFD7DAE2)
